{
	"11001": "Not detected license, please configure a legal license",
	"11002": "Illegal license, maybe not match the current server hardware",
	"11003": "License expired",
	"11011": "System has not been initialized",
	"11012": "The current user have no permission to initialize",
	"11021": "Compute node version does not match",
	"11022": "Client version does not match",
	"11023": "Version of upgrade package is older, unable to upgrade",
	"11024": "Not detected upgrade package, please upload upgrade package first",
	"11025": "Upgrade abnormally",
	"11031": "File size exceeds the limitation, maximum is 2G",
	"11032": "The file already exists",
	"11033": "Operating system cannot be detected",
	"11034": "The specified operating system type is inconsistent with detected system",
	"11041": "Backup file does not exist",
	"11042": "Repeated backup file name",
	"12001": "Not detected console node",
	"12002": "Not detected compute node",
	"12003": "Multiple console nodes existed",
	"12004": "The console node is unavailable",
	"12005": "Specified compute node is unavailable",
	"12006": "Not detected specified compute node in database",
	"12007": "No available compute nodes",
	"12011": "Server is not running",
	"12012": "Server time is not synchronous",
	"12013": "The server has no ROOT password",
	"12014": "Server ROOT password error",
	"12015": "The maximum running desktop amount of server is 0",
	"12016": "There is desktop in server, unable to be deleted",
	"12017": "There is template in server, unable to be deleted",
	"12021": "HOST restarts the service is abnormal, please check the HOST situation and if ROOT password is correct.",
	"12022": "Download HOST log is abnormal, please check the host start situation and check if the  ROOT password is normal",
	"12023": "Modify NIC failed",
	"12024": "The IP already exists, please configure other un-used IP",
	"12031": "Server memory resources is insufficient",
	"12032": "System disk space of server is insufficient",
	"12033": "Data disk space of server is insufficient",
	"12040": "Please configure storage first",
	"12041": "Add storage abnormally",
	"12042": "Delete memory abnormally",
	"12043": "Storage resources name is repeat",
	"12044": "You can only add a local storage",
	"12045": "Before deleting, please delete all virtual machines on storage",
	"12046": "Please configure SCSI storage first",
	"12047": "Please configure LUN on SCSI on storage first",
	"12048": "Not detected FC LUN, please add first",
	"12050": "Not detected corresponding network segment",
	"12051": "Not detected corresponding IP",
	"12052": "The remaining IP is not enough",
	"12053": "Create network segment failed",
	"12054": "Add the new IP failed",
	"12055": "Not detected the specified network in database",
	"12056": "The network already exists",
	"12057": "The IP already exists",
	"12058": "The network is being used",
	"12061": "IP is out of the range",
	"12062": "Gateway is not in the scope",
	"12063": "IP format error",
	"12064": "Gateway format error",
	"12065": "Network format error",
	"12066": "Start IP can not be behind the end IP",
	"12067": "Network is “NULL”",
	"12068": "VLAN ID is not set",
	"13011": "Not detected the specified template in database",
	"13012": "Template file lost",
	"13013": "Save template failed",
	"13014": "Download template abnormally",
	"13021": "Template name already exists",
	"13022": "Load ISO failed",
	"13023": "Operating system or “Tools” is not installed completely",
	"13031": "The template has not been finished or is being edited, updated, unable to download",
	"13041": "The template exists related desktop",
	"13042": "",
	"13051": "The template exists related personal desktop, unable to  update",
	"13052": "Update template abnormally",
	"13053": "The template has no associated scenes",
	"13054": "BASE located server is not available",
	"13081": "The template exists related scene, unable to be deleted",
	"13082": "The template exists related desktop, unable to be deleted",
	"13083": "Template name repeated",
	"14011": "Not detected the desktop in database",
	"14012": "Desktop file lost",
	"14013": "Not detected the scene in database",
	"14014": "Reboot abnormally",
	"14015": "Start abnormally",
	"14016": "Shutdown abnormally",
	"14017": "Active scene failed, please re-activate",
	"14021": "Please firstly close the desktop, and then modify",
	"14022": "Must delete the snapshot before modifying desktop",
	"14023": "The desktop exist schedule plan, unable to be deleted",
	"14024": "The desktop is being using, unable to be deleted",
	"14031": "The user name or computer name prefix has been used",
	"14032": "Rollback scene failed",
	"14033": "Please firstly close the scene, and then perform operation",
	"14034": "The scene already exists schedule plan, unable to be  deleted",
	"14041": "Desktop is on living migration",
	"14042": "Not detected shared memory, unable to live migration",
	"14043": "Not specified the target host in Living migration",
	"14051": "Snapshot name cannot be empty",
	"14052": "Unable to add snapshot when enabled USB",
	"14053": "Snapshot number reaches to upper limit",
	"14054": "Snapshot must be in running state",
	"14055": "Restore snapshot must shut down the virtual machine firstly",
	"14063": "Only the running desktop can be paused",
	"14064": "Only the paused desktop can be restored",
	"14071": "No available host to create virtual machine",
	"14072": "The amount of users and desktops must be the same",
	"14073": "Related users’ amount exceeded",
	"14074": "Lack of available IP amount",
	"15011": "Client is not online",
	"15012": "Client has no associated classroom",
	"15013": "Client didn’t configure serial number",
	"15014": "Client connection is timeout",
	"15021": "When set terminal fixed IP in batch, available IP amount is less than terminal amount",
	"15022": "IP is not in legal network segment, please check and re-input",
	"15023": "IP format is error, please check and re-input",
	"15031": "The client is being using, unable to be deleted",
	"16011": "Not detected the scene in database",
	"16012": "The class name already exists",
	"16021": "Not specified the class ID when modify class",
	"16022": "Not specified the classroom name when modify classroom",
	"16031": "The classroom exists terminal, unable to be deleted",
	"16032": "The classroom exists scene, unable to be deleted",
	"17001": "Please log in first",
	"17002": "The user is not exist",
	"17003": "Login password error",
	"17004": "The current user is not administrator user",
	"17005": "No admin user",
	"17011": "User name is empty",
	"17012": "Password is empty",
	"17013": "The login name already exists",
	"17014": "The Email already exists",
	"17021": "The file is illegal, please re-import",
	"18022": "User’s data is empty, please re-import",
	"17031": "There is a user’s role is empty, please check and re-import",
	"17032": "There is a user’s sex is empty, please check and re-import",
	"17033": "There is a user’s password is empty, please check and re-import",
	"17034": "There is a user’s name is empty, please check and re-import",
	"17041": "There is a user’s name is repeat, please check and re-import",
	"17051": "There is a user’s role format error, please check and re-import",
	"17052": "There is a user’s sex format error, please check and re-import",
	"17053": "There is a user’s password format error, please check and re-import",
	"17054": "There is a user’s Email format error, please check and re-import",
	"17055": "There is a user's phone format error, please check and re-import",
	"17061": "The user has been bound with  desktop, unable to be deleted",
	"18010": "Monitoring service is not enable. Please check and enable it.",
	"18011": "No monitoring data collected",
	"18012": "Monitoring data has no unit",
	"19997": "Request is illegal",
	"19998": "System is busy, please try again later",
	"19999": "System is abnormal, please contact administrator",
	"20001": "Storage mounted error",
	"20002": "Not detected FC storage",
	"20013": "No image file",
	"20014": "Not detected image file",
	"20015": "Image file is invalid",
	"20021": "Lock desktop failed",
	"20022": "Desktop is not running",
	"20023": "Virtual machine already exists",
	"20024": "Virtual machine process is invalid",
	"20025": "Virtual machine memory is invalid",
	"20026": "Create virtual machine failed",
	"20027": "Not detected virtual machine",
	"20028": "Not detected Virtual machine in database",
	"20029": "Startup desktop failed",
	"20030": "Virtual machine destruction failed",
	"20031": "Please firstly shutdown the virtual machine and then try again",
	"20032": "Please firstly pause the virtual machine and then try again",
	"20033": "Pause virtual machine failed",
	"20034": "Restore virtual machine failed",
	"20035": "Please sleep virtual machine and then try again",
	"20036": "Sleep virtual machine failed",
	"20037": "Please reset virtual machine size  and then try again",
	"20038": "Resize virtual machine failed",
	"20039": "Virtual machine is running",
	"20040": "Storage resource is insufficient",
	"20051": "Reset disk size failed",
	"20052": "Image does not exist, unable to reset the size",
	"20053": "Storage space is insufficient, unable to reset the size",
	"20054": "Not detected disk",
	"20055": "Disk space is insufficient",
	"20060": "Not support to create snapshot",
	"20061": "Not found snapshot",
	"20062": "Exceeds snapshots quantity",
	"20063": "Restore snapshot failed",
	"20064": "Snapshot does not exist",
	"20070": "Virtual machine migration requires all services are running",
	"20080": "Not detected NIC",
	"20081": "Modified IP is not available",
	"20082": "Not detected the modified IP",
	"20083": "Network initialization failed",
	"20084": "Not found floating IP",
	"20090": "Not detected ISCSI target",
	"20091": "Device path is invalid",
	"20092": "Shared storage deployment does not take effect",
	"20093": "“Libvirt “ storage does not exist",
	"20094": "Request ISCSI failed",
	"20100": "Memory resource is insufficient",
	"20110": "NFS storage deployment error",
	"20120": "Database error",
	"20130": "Hypervisor type is invalid",
	"20131": "Specified Hypervisor is too old",
	"20132": "Dynamic migration failed",
	"20140": "Remote connection reuse invalid",
	"20141": "Not detected API service",
	"50003": "Boot desktop failed, please contact administrator",
	"50004": "License has expired, please contact administrator",
	"50005": "Exceeds the maximum connection amount",
	"50006": "Username or password error",
	"50007": "Domain username or password error",
	"50008": "Please register terminal firstly",
	"50010": "No available scenes",
	"50011": "Haven’t bound to any desktop",
	"50012": "No available virtual machine in current scene, please contact administrator",
	"50013": "The client is not configured or configured wrong login sequence number",
	"50014": "Password is illegal",
	"50015": "The template name already exists, please re-input",
	"50016": "Parameter is illegal",
	"50017": "Not allowed to use the sequence number",
	"50018": "Teacher’s machine is not turned on, unable to obtain it’s IP",
	"PAI_CODE": "Error code"
}